# -*- coding: utf-8 -*-
"""Untitled78.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ldVXslCGbq_99P28BwJwyxb794D6uuF6
"""

n = int(input('Digite o valor de n: '))

# Verificar se n é igual a 0
if n == 0:
    f = 1
else:
    f = n
    for i in range(1, n):
        f *= i

print(f)